[package]
name = "vrs"
description = "Verifiable Reed-Solomon Encoding (VRS) implementations."
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "^1.0"
ark-ff = { version = "^0.5.0", default-features = false }
ark-std = { version = "^0.5.0", default-features = false }
